### PR TITLE
Add run script tips

### PR DESCRIPTION
**Pull request by mischah**
This PR adds tips regarding:
- Passing options to used commands
  - *Something that wasn’t obvious for me*
- Silent option
  - *Something I just learned about*

Cheers, Michael

### CODE REVIEW

**Review by elektronik2k5 — APPROVED** [review]

**Comment by mischah** [comment]
Hej, is there something I can approve in terms of wording or content?
Or is this PR out of scope.

Cheers, Michael

**Comment by mischah** [comment]
🛎

**Comment by sindresorhus** [comment]
Thanks for your patience. This one took a while to get to. Too many PRs...

**Comment by sindresorhus** [comment]
This looks great. Thank you :)

**Comment by mischah** [comment]
Your welcome 💖 

> Thanks for your patience. This one took a while to get to. Too many PRs…

I can barely imagine with how many PRs you have to deal.

Thank you.

**Pull request merged**
