### PR TITLE
+searchlibs

### PR DESCRIPTION
**Pull request by cztomsik**
Another site where you can search npm packages. 
- it gives better results than anything else known to me
- results are shown (and sorted) in a table with more metrics so it's easier to choose
- you can filter out things you don't care, for example searching "format" returns some results related to markdown which I'd like to leave out so I can try "format -markdown"
- it's also possible to do something like "(react | angular) components"

http://searchlibs.com

### CODE REVIEW

**Comment by sindresorhus** [comment]
> it gives better results than anything else known to me

I don't think you have tried https://npms.io/ then. It gives much better results than this.

**Comment by sindresorhus** [comment]
The metrics are too simplistic. For example, just because a repo haven't been touched in a while, doesn't make it less good. There are many more factors to take into account. Sometimes a project is just done. I would recommend reading: https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md For example, http://searchlibs.com/#terminal colors doesn't even return the most used terminal coloring library on npm. The number of releases is also useless without more context. Users might be tricked into thinking more releases equals better quality.

This looks like a good start, but I don't think it's something I would recommend yet.

**Comment by cztomsik** [comment]
- chalk is there, it's just hidden because its latest release is 14 months ago
- you're right that in **SOME** cases it really makes sense to search even for outdated libs (which you can)

here's a list of few common cases where it gives better results than npms:
- date
- slider
- database
- number
- logging

of course there will be cases when npms will be better but it will be less and less often, I hope.

**Comment by swyxio** [comment]
ice cold rejection!

**Pull request closed without merging**
