### PR TITLE
Add info about npm lifecycle scripts

### LINKED ISSUE #6: Mention lifecycle scripts
In your "Run scripts" section, it might be worth mentioning that you can tell npm to automatically run scripts before or after certain lifecycle events of your package, e.g. `pretest`, `prepublish` or `postinstall`:

``` json
{
  "name": "the-awesomest",
  "scripts": {
    "pretest": "xo",
    "test": "npm run prepublish && nyc ava",
    "prepublish": "babel lib --out-dir=dist",
    "postinstall": "echo 'Thanks for installing The Awesomest'"
  },
  "devDependencies": {
    "ava": "^0.9.1",
    "babel": "^6.3.26",
    "nyc": "^5.0.1",
    "xo": "^0.12.1"
  },
  "xo": {
    "esnext": true
  }
}
```

A link to https://docs.npmjs.com/misc/scripts might be helpful too.

### PR DESCRIPTION
**Pull request by mischah**
Closes #6

Feedback is welcome 😊

### CODE REVIEW

**Comment by mischah** [comment]
Hej Sindre, is there something I can do to get this one and #62 merged?

I’d be happy to help 😘

Cheers, Michael

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by mischah** [comment]
Sure … ✅

**Comment by sindresorhus** [comment]
Looks great 🙏 Sorry for the long delay.

**Comment by mischah** [comment]
Thanks. And no problem. I know you have more than a couple of projects to maintain.

**Pull request merged**
