### PR TITLE
Add `keywords`

### PR DESCRIPTION
**Pull request by gillstrom**
> CLI utility for easily adding keywords to package.json.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
Actually, I don't really see the point of this module. All it does is to add keywords to package.json.

Would rather add something more general like https://github.com/zeke/npe.

**Comment by sindresorhus** [comment]
Thanks for the suggestion though. Keep'em coming :)

https://github.com/sindresorhus/awesome-npm/commit/987cd4d812c2703cb7a4c07d15c3caa8a6229979

**Comment by gillstrom** [comment]
That's a much better one, thanks!

**Pull request closed without merging**
