### PR TITLE
Add a couple of tips for using `npx`

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Seeing as this comes bundled with latest Node.js, I think it would be better as an entry in the Tips section showing how you can use it and why it's useful.

**Comment by sobolevn** [comment]
Agreed, there is an awesome article wrote by `npx` author: https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

I can take some examples from there. And also link to the original article.

**Comment by sindresorhus** [comment]
Sounds good

**Comment by sobolevn** [comment]
@sindresorhus done!

**Pull request merged**
