### PR TITLE
Add john

### PR DESCRIPTION
**Pull request by davej**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Creative take on solving the problem. Though, I'd personally rather see something that de-deduplicates dependencies, like how it would look if you installed with npm2.

**Comment by davej** [comment]
You mean just unflattening the modules so that they're nested?

**Comment by sindresorhus** [comment]
Yup, but that doesn't just mean unflattening, but also duplicating where they were deduplicated.

**Comment by davej** [comment]
Yeah, that would be useful. There's probably quite a bit of nuance required around updating/uninstalling/pruning/etc.. modules after your tree has been dededuped though. Or maybe it would just work, I'm not familiar enough with the npm3 internals to know.

Personally, I find flat trees useful, particularly for Electron stuff (`node_modules` dir tends to take up less space and path lengths are shorter for Windows).

**Pull request merged**
