### PR TITLE
Add check for outdated packages command.

### PR DESCRIPTION
**Pull request by appleboy**
cc @sindresorhus

### CODE REVIEW

**Comment by sindresorhus** [comment]
When would you use this over better tools like `david` or `npm-check`? Having it output all possible outdated packages, even once already matching the semver range, doesn't seem very useful to me, but I might be missing a use-case.

https://github.com/sindresorhus/awesome-npm#other

**Comment by appleboy** [comment]
@sindresorhus 

I think `npm-check` would be better than `npm outdated` command. I just supply alternative way to  display outdated packages informations for someone.

Thanks.

**Comment by sindresorhus** [comment]
Ok, gonna pass on this then. Everything in this list has a purpose. Just having something "because" is not a good reason unfortunately.

**Comment by appleboy** [comment]
@sindresorhus OK Thanks.

**Pull request closed without merging**
