### PR TITLE
Add article "Npm Needs a Personal Trainer"

### PR DESCRIPTION
**Pull request by coreybutler**
I've had several folks tell me they found this useful. It's slightly older, but I believe still relevant.

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's a good message. Package obesity is a real problem. I've been fighting it a lot. 

Why did you not mention the "files" field in package.json? It solves the problem a lot better by whitelisting what you want included in the package instead of having a long often outdated list of things you want to ignore.

## 

Relevant to your Underscore argument: https://github.com/jashkenas/underscore/pull/1054 https://github.com/jashkenas/underscore/pull/1213

**Comment by coreybutler** [comment]
I agree, the `files` attribute is a cleaner approach. I wrote that before I was aware of the files attribute. Frankly, I forgot to go back and add that... I think I'll update the article today. Thanks for the prompt to do so!

Totally just opining at this point, but I'd love to see Node become an example of how to keep a more laser-like focus on what matters for systems dev/management. I'd also love to see the Docker community follow suit.... talk about bloat!

**Comment by coreybutler** [comment]
Haha, in re-reading it, I DID add a line about the files. But it's not prominent enough, so I'll still update it.

**Comment by sindresorhus** [comment]
Can you add a very short description after the link of what the article is about? Not clear from the title.

**Comment by coreybutler** [comment]
Done.

**Comment by coreybutler** [comment]
Thanks!

**Pull request closed without merging**
